<?php

namespace Joki\Bundle\JokiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrderNRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderNRepository extends EntityRepository
{
}
